FPS_TARGET = 30

FACE_MESH_MAX_FACES = 1
FACE_MESH_MIN_DETECTION_CONFIDENCE = 0.5
FACE_MESH_MIN_TRACKING_CONFIDENCE = 0.5
REFERENCE_IPD_PX = 100.0

EMOTION_CADENCE = 3
EMA_ALPHA = 0.35

WINDOW_LEN_S = 3.0
BOB_FREQ_LO = 0.5
BOB_FREQ_HI = 3.0
VIBE_PLV_WEIGHT = 0.6
VIBE_PERIOD_WEIGHT = 0.4
PERIOD_TOLERANCE = 0.20

DEFAULT_BPM = 120.0
